server:
  port: 8778

spring:

  datasource:
    url: jdbc:mysql://localhost:3307/demo_clone?useSSL=false
    username: root
    password: 12345
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: INFO
    com.example: DEBUG